### ISSUE TITLE
Getting following error as I hit recognise. Am I missing any step ?

### ISSUE THREAD

**Issue by krushal-kyada** [wodin/expo-ocr-example#1]
null is not an object (evaluating '_reactNativeTesseractOcr.default.recognize')
at App.js:68:35 in recognizeTextFromImage
at App.js:63:33 in recognizeTextFromImage
at App.js:93:36 in Button.props.onPress
at node_modules/react-native/Libraries/Pressability/Pressability.js:691:17 in _performTransitionSideEffects
at node_modules/react-native/Libraries/Pressability/Pressability.js:628:6 in _receiveSignal
at node_modules/react-native/Libraries/Pressability/Pressability.js:524:8 in responderEventHandlers.onResponderRelease

**Comment by epoq** [comment]
hello , i have the same issue ===> null is not an object (evaluating '_reactNativeTesseractOcr.default.recognize')

**Comment by wodin** [comment]
Hi. Did you build with `eas build`?

`react-native-tesseract-ocr` depends on native code, so you need to build with `eas build` instead of `expo build`. Also, this won't work in Expo Go. You need to build a custom dev client (with `eas build --profile development`)

**Comment by wodin** [comment]
I've updated the app to use ML Kit Text recognition. You'll still need to create a development build. It will not work in Expo Go.

See [Introduction to development builds](https://docs.expo.dev/develop/development-builds/introduction/) in the Expo docs
